# Slack Settings
SLACK_TOKEN = ""
SLACK_CHANNEL = ""

# Telegram Settings
TELEGRAM_TOKEN = ""
TELEGRAM_CHAT_ID = ""

# Email Settings
EMAIL_HOST = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_PORT = ""
EMAIL_SENDER = ""
EMAIL_RECEIVE = [""]
